#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

key=$(ynh_string_random --length=45 | base64)
ynh_app_setting_set --key=key --value=$key

redis_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --key=redis_db --value=$redis_db

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building $app..."

yarn global add svgo@1.3.2

pushd "$install_dir/"

    # Install dependencies
    export RAILS_ENV=production 
    ynh_exec_as_app bundle config deployment 'true'
    ynh_exec_as_app bundle config without 'development test'
popd

#=================================================
# CONFIGURE APP
#=================================================
ynh_script_progression "Configuring $app..."

pushd "$install_dir/"
    ynh_exec_as_app RAILS_ENV=production bundle exec rails credentials:edit
    ynh_exec_as_app RAILS_ENV=production DATABASE_URL=postgresql://$db_user:$db_pwd@:5432/$db_name bundle exec rails db:migrate
    ynh_exec_as_app RAILS_ENV=production DATABASE_URL=postgresql://$db_user:$db_pwd@:5432/$db_name bundle exec rails db:seed
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="$app’s service" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate
mkdir -p /var/log/$app
touch /var/log/$app/$app.log

# Create a dedicated Fail2Ban config
# ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
