#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=""

#=================================================
# APP CONFIGURATION
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building $app..."

pushd "$install_dir/"
    # Install dependencies
    export RAILS_ENV=production

    # Specify gems path (missing from the docs :/)
    # Use "--local" to apply only for this directory
    ynh_exec_as_app bundle config set --local path 'vendor/bundle'
    ynh_exec_as_app bundle config set --local deployment 'true'
    ynh_exec_as_app bundle config set --local without 'development test'

popd

#=================================================
# CONFIGURE APP
#=================================================
ynh_script_progression "Configuring $app..."

pushd "$install_dir/"
    export RAILS_ENV=production
    # Sadly, this is a manual step for first install: "credentials:edit" opens a text editor (nano/vim),
    # so you can add some values specific to the deployment. Once the editor closes, the file is hashed
    # with the master key, which is also specific to the deployment.
    #
    # It is possible to use environment variables instead. Note that these values should be different for every instance:
    #export RAILS_MASTER_KEY=0000 # In theory, can be left as is, at it is only used to decrypt the file containing "SECRET_KEY_BASE"
    export SECRET_KEY_BASE=$key_base # used to hash password and cookies
    export INSTANCE_SECRET_KEY_JWT=$key # Used to generate JWT tokens
    #ynh_exec_as_app bundle exec rails credentials:edit

    # In general, you can use SECRET_KEY_BASE_DUMMY=1 for commands that don't require the
    # SECRET_KEY_BASE or the INSTANCE_SECRET_KEY_JWT: it prevent Rails from checking for valid values.
    # The downside is if you generate passwords or JWT tokens with it, they won't be valid.
    # We won't use it for the migrations but we could.
    ynh_exec_as_app RAILS_ENV=production INSTANCE_SECRET_KEY_JWT=$key SECRET_KEY_BASE_DUMMY=$key_base DATABASE_URL=postgresql://$db_user:$db_pwd@localhost:5432/$db_name bundle exec rails db:migrate
    # valid key base is required for this
    ynh_exec_as_app RAILS_ENV=production INSTANCE_SECRET_KEY_JWT=$key SECRET_KEY_BASE=0000 DATABASE_URL=postgresql://$db_user:$db_pwd@localhost:5432/$db_name bundle exec rails db:seed
popd

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="$app’s service" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate
mkdir -p /var/log/$app
touch /var/log/$app/$app.log

# Create a dedicated Fail2Ban config
# ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
