#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers
source ynh_mise
source ynh_ruby
source ynh_nodejs

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

ynh_ruby_install
ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=""

#=================================================
# APP CONFIGURATION
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Bundle install..."

pushd "$install_dir/"
    # Specify gems path (missing from the docs :/)
    # Use "--local" to apply only for this directory
    ynh_exec_as_app RAILS_ENV=production bundle config set --local path 'vendor/bundle'
    ynh_exec_as_app RAILS_ENV=production bundle config set --local deployment 'true'
    ynh_exec_as_app RAILS_ENV=production bundle config set --local without 'development test'
    ynh_hide_warnings ynh_exec_as_app RAILS_env=production bundle install
popd

#=================================================
# CONFIGURE APP
#=================================================
ynh_script_progression "Configuring $app..."

pushd "$install_dir/"
    ynh_exec_as_app RAILS_ENV=production INSTANCE_SECRET_KEY_JWT=$key SECRET_KEY_BASE_DUMMY=$key_base DATABASE_URL=postgresql://$db_user:$db_pwd@localhost:5432/$db_name bundle exec rails db:migrate
    ynh_exec_as_app RAILS_ENV=production INSTANCE_SECRET_KEY_JWT=$key SECRET_KEY_BASE=0000 DATABASE_URL=postgresql://$db_user:$db_pwd@localhost:5432/$db_name bundle exec rails db:seed
popd

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="$app’s service" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate
mkdir -p /var/log/$app
touch /var/log/$app/$app.log

# Create a dedicated Fail2Ban config
# ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
